app/web/audiseum/android/urls.py
from django.urls import path, re_path
import android.views

app_name = 'android'

urlpatterns = [
    re_path('izlozak(?P<izlozak_id>[0-9]+)/naslov', android.views.android_naslov, name='android_naslov'),
    re_path('izlozak(?P<izlozak_id>[0-9]+)/text', android.views.android_text, name='android_text'),
    re_path('izlozak(?P<izlozak_id>[0-9]+)/audio', android.views.android_audio, name='android_audio'),
    re_path('izlozak(?P<izlozak_id>[0-9]+)/slika', android.views.android_slika, name='android_slika'),
    path('registracija/', android.views.register, name='registracija'),
    path('prijava/', android.views.prijava, name='login'),

    path('statistika/<unique_id>/<izlozak_id>', android.views.android_statistika),
    path('povezi/<unique_id>', android.views.povezi),
    path('odvezi/<unique_id>', android.views.izbrisi_povezanost),
    path('provjeri/<unique_id>', android.views.jel_povezan),
]

app/web/audiseum/audiseum/urls.py
from django.contrib import admin
from django.urls import include, path
import izlosci.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', izlosci.views.index, name='index'),
    path('izlosci/', include('izlosci.urls')),
    path('statistika/', include('statistika.urls')),
    path('android/', include('android.urls')),
]

app/web/audiseum/izlosci/urls.py
from django.urls import path
import izlosci.views
import statistika.views


app_name = 'izlosci'

urlpatterns = [
    path('', izlosci.views.izlosci, name='izlosci'),
    path('grupa/<grupa_id>/', izlosci.views.izlosci_grupa, name='izlosci_grupa'),
    path('izlozak/<izlozak_id>/', izlosci.views.izlozak, name='izlozak'),
    path('promo-materijali/', izlosci.views.promo_materijali, name='promo_materijali'),
    path('registracija/', izlosci.views.register, name='registracija'),
    path('activate/<uidb64>/<token>/', izlosci.views.activate, name='activate'),
    path('prijava/', izlosci.views.prijava, name='login'),
    path('odjava/', izlosci.views.odjava, name='odjava'),
    path('uredi-osobne-podatke/', izlosci.views.uredi_osobne_podatke, name='uredi_osobne_podatke'),
    path('promijeni-lozinku', izlosci.views.promijeni_lozinku, name='promijeni_lozinku'),
    path('../statistika', statistika.views.statistika, name='statistika'),
    path('dodaj-admina/', izlosci.views.dodaj_admina, name='dodaj_admina'),
    path('ovlast/', izlosci.views.dodaj_admin_ovlast, name='ovlast'),
    path('dodaj-izlozak/', izlosci.views.dodaj_izlozak, name='dodaj_izlozak'),
    path('uredi-izlozak/<izlozak_id>/', izlosci.views.uredi_izlozak, name='uredi_izlozak'),
    path('obrisi-izlozak/<izlozak_id>/', izlosci.views.obrisi_izlozak, name='obrisi_izlozak'),
    path('dodaj-grupu/', izlosci.views.dodaj_grupu, name='dodaj_grupu'),
    path('dodaj-promo-materijal', izlosci.views.dodaj_promo_materijal, name='dodaj_promo_materijal'),
    path('reprodukcija/<izlozak_id>', izlosci.views.reproduciraj, name='reproduciraj'),

]

app/web/audiseum/statistika/urls.py
from django.urls import path
from . import views

app_name = 'statistika'

urlpatterns = [
    path('', views.statistika, name='statistika'),
    path('<param>', views.statistika_sort, name='statistika_sort')
]

app/web/audiseum/statistika/views.py
from django.shortcuts import render
from izlosci.models import (
    StatistikaPosjecenosti, Izlozak,
    StranicaIzlozak, GrupaIzlozaka,
    StatistikaReprodukcije, ZvucniZapis)
from izlosci.forms import (
    UrediOsobnePodatkeForm, PromijeniLozinkuForm,
    AddAdminForm, AdminOvlastForm,
    DodajIzlozakForm, AddGroupForm,
    PromoMaterijalForm)
from django.contrib.auth.models import User
from operator import itemgetter, attrgetter
from django.contrib.sessions.models import Session
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse


@login_required
def statistika(request):

    if not request.user.groups.filter(name__in=['administratori', 'vlasnik']).exists():
        return HttpResponse("Zabranjeno")

    strIzlozak = StranicaIzlozak.objects.all()
    statPosjObj = StatistikaPosjecenosti.objects.all()
    statistikaReprodukcija = StatistikaReprodukcije.objects.all()
    pocetna = StatistikaPosjecenosti.objects.get(idstranica=0)

    ukupno = 0

    for stat in statPosjObj:
        ukupno += stat.brojprikaza

    izlosci = Izlozak.objects.all().order_by('nazivizlozak')

    for izlozak in izlosci:
        sum = 0
        for user in User.objects.all():
            for statistikaRedak in statistikaReprodukcija:
                if izlozak.idzvucnizapis == statistikaRedak.idzvucnizapis and user.id == statistikaRedak.korisnik_id:
                    sum += 1
                    break
        izlozak.idzvucnizapis.brojkorisnika = sum

    statPosj = []
    for s in statPosjObj:
        if s.idstranica != 0:
            tup = (s.stranicaizlozak_set.first().idizlozak.nazivizlozak,
                   s.brojprikaza,
                   "%d sati i %d minuta" % (s.vrijemezadrzavanja.seconds//3600, (s.vrijemezadrzavanja.seconds//60) % 60))
            statPosj.append(tup)

    statPosj = sorted(statPosj)
    sveGrupe = GrupaIzlozaka.objects.all().order_by('nazivgrupa')
    grupeSPodgrupama = set()
    for grupa in sveGrupe:
        if grupa.idgrupa == grupa.idnadgrupa:
            for podgrupa in sveGrupe:
                if podgrupa.idnadgrupa == grupa.idgrupa and podgrupa.idgrupa != podgrupa.idnadgrupa:
                    grupeSPodgrupama.add(grupa.idgrupa)
                    break

    active_sessions = Session.objects.filter(expire_date__gte=timezone.now())
    user_id_list = []
    for session in active_sessions:
        data = session.get_decoded()
        user_id_list.append(data.get('_auth_user_id', None))
    # Query all logged in users based on id list
    prijavljeni_korisnici = User.objects.filter(id__in=user_id_list).count()

    context = {
        'pocetna': pocetna,
        'strIzlozak': strIzlozak,
        'statPosj': statPosj,
        'ukupno': ukupno,
        'izlosci': izlosci,
        'sveGrupe': sveGrupe,
        'grupeSPodgrupama': grupeSPodgrupama,
        'add_admin_form': AddAdminForm(),
        'admin_ovlast_form': AdminOvlastForm(),
        'izlozak_form': DodajIzlozakForm(),
        'prijavljeni_korisnici': prijavljeni_korisnici
    }
    return render(request, 'statistika/statistika.html', context)


def statistika_sort(request, param):
    strIzlozak = StranicaIzlozak.objects.all()
    statPosjObj = StatistikaPosjecenosti.objects.all()
    statistikaReprodukcija = StatistikaReprodukcije.objects.all()
    pocetna = StatistikaPosjecenosti.objects.get(idstranica=0)

    ukupno = 0

    for stat in statPosjObj:
        ukupno += stat.brojprikaza

    izlosci = Izlozak.objects.all()
    if param == 'reprodukcija_stranica':
        izlosci = sorted(izlosci, key=attrgetter('nazivizlozak'))
    elif param == 'reprodukcija_korisnik':
        zvucni_zapisi = ZvucniZapis.objects.all().order_by('brojkorisnika')
        izlosci = []
        for zapis in zvucni_zapisi:
            izlosci.append(Izlozak.objects.get(idzvucnizapis=zapis.idzvucnizapis))
        izlosci.reverse()
    elif param == 'reprodukcija_ukupno':
        zvucni_zapisi = ZvucniZapis.objects.all().order_by('brojreprodukcija').reverse()
        izlosci = []
        for zapis in zvucni_zapisi:
            izlozak = Izlozak.objects.get(idzvucnizapis=zapis.idzvucnizapis)
            if izlozak is not None:
                izlosci.append(izlozak)

    for izlozak in izlosci:
        sum = 0
        for user in User.objects.all():
            for statistikaRedak in statistikaReprodukcija:
                if izlozak.idzvucnizapis == statistikaRedak.idzvucnizapis and user.id == statistikaRedak.korisnik_id:
                    sum += 1
                    break
        izlozak.idzvucnizapis.brojkorisnika = sum

    statPosj = []
    for s in statPosjObj:
        if s.idstranica != 0:
            tup = (s.stranicaizlozak_set.first().idizlozak.nazivizlozak,
                   s.brojprikaza,
                   "%d sati i %d minuta" % (s.vrijemezadrzavanja.seconds//3600, (s.vrijemezadrzavanja.seconds//60) % 60))
            statPosj.append(tup)

    if param == 'posjecenost_stranica':
        statPosj = sorted(statPosj, key=itemgetter(0))
    elif param == 'posjecenost_prikaz':
        statPosj = sorted(statPosj, key=itemgetter(1), reverse=True)
    elif param == 'posjecenost_vrijeme':
        statPosj = sorted(statPosj, key=itemgetter(2), reverse=True)

    sveGrupe = GrupaIzlozaka.objects.all().order_by('nazivgrupa')
    grupeSPodgrupama = set()
    for grupa in sveGrupe:
        if grupa.idgrupa == grupa.idnadgrupa:
            for podgrupa in sveGrupe:
                if podgrupa.idnadgrupa == grupa.idgrupa and podgrupa.idgrupa != podgrupa.idnadgrupa:
                    grupeSPodgrupama.add(grupa.idgrupa)
                    break

    active_sessions = Session.objects.filter(expire_date__gte=timezone.now())
    user_id_list = []
    for session in active_sessions:
        data = session.get_decoded()
        user_id_list.append(data.get('_auth_user_id', None))
    # Query all logged in users based on id list
    prijavljeni_korisnici = User.objects.filter(id__in=user_id_list).count()

    context = {
        'pocetna': pocetna,
        'strIzlozak': strIzlozak,
        'statPosj': statPosj,
        'ukupno': ukupno,
        'izlosci': izlosci,
        'sveGrupe': sveGrupe,
        'grupeSPodgrupama': grupeSPodgrupama,
        'add_admin_form': AddAdminForm(),
        'admin_ovlast_form': AdminOvlastForm(),
        'izlozak_form': DodajIzlozakForm(),
        'prijavljeni_korisnici': prijavljeni_korisnici
    }
    return render(request, 'statistika/statistika.html', context)

app/web/audiseum/statistika/templates/statistika/adminView.html
{% extends './statistika.html' %}

{% block admin %}
<div class="btn-group-vertical">
    {% block vlasnik-izbornik %}
    {% endblock %}
    <button type="button" class="btn btn-outline-dark" aria-hidden="true" data-toggle="modal"
            data-target="#exibitModal">
        <span class="fa fa-plus"></span>
        Dodaj izložak
    </button>
    <button type="button" class="btn btn-outline-dark" aria-hidden="true" data-toggle="modal"
            data-target="#groupModal">
        <span class="fa fa-plus"></span>
        Dodaj grupu
    </button>
</div>

<div class="btn-statistika">
    <a class="btn btn-outline-dark" href="{% url 'izlosci:statistika' %}" role="button">Statistika</a>
</div>

<div class="modal fade" id="exibitModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <h5>Dodavanje izloška</h5>
                    </div>
                </div>
            </div>

            <div class="modal-body">
                <form role="form">
                    <div class="form-group">
                        <label for="nameExibit">Naziv</label>
                        <input type="text" class="form-control" id="nameExibit" placeholder="Upišite naziv izloška">
                    </div>
                    <div class="form-group">
                        <label for="description">Opis</label>
                        <textarea class="form-control" id="description" placeholder="Upišite opis izloška"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="grupaIzloska">Grupa</label>
                        <select multiple class="form-control" id="grupaIzloska">
                            {% for grupa in sveGrupe %}
                            <option>{{ grupa.nazivgrupa }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="image">Slika</label>
                        <input type="file" class="form-control-file" id="image">
                    </div>
                    <div class="form-group">
                        <label for="audio">Zvučni zapis</label>
                        <input type="file" class="form-control-file" id="audio">
                    </div>
                    <div class="form-group">
                        <input type="submit" class="form-control btn btn-success" value="Dodaj izložak">
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col-3">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal" aria-label="Close">
                                Zatvori
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="groupModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <h5>Dodavanje grupe izložaka</h5>
                    </div>
                </div>
            </div>

            <div class="modal-body">
                <form role="form">
                    <div class="form-group">
                        <label for="nameGroup">Naziv</label>
                        <input type="text" class="form-control" id="nameGroup" placeholder="Upišite naziv grupe">
                    </div>
                    <div class="form-group">
                        <label for="nadgrupa">Nadgrupa</label>
                        <select multiple class="form-control" id="nadgrupa">
                            {% for grupa in sveGrupe %}
                            {% if grupa.idgrupa == grupa.idnadgrupa %}
                            <option>{{ grupa.nazivgrupa }}</option>
                            {% endif %}}
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="form-control btn btn-success" value="Dodaj grupu izložaka">
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col-3">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal" aria-label="Close">
                                Zatvori
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% block vlasnik-modal %}
{% endblock %}
{% endblock %}

app/web/audiseum/statistika/templates/statistika/statistika.html
{% extends 'base.html' %}

{% block main %}
<!--prikaz statistike-->
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-4 col-lg-4 col-md-5 col-sm-7">
            <h4>Broj trenutno aktivnih korisnika: {{ prijavljeni_korisnici }}</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-4 col-lg-4 col-md-5 col-sm-7">
            <h4>Ukupna posjećenost: {{ ukupno }}</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
            <h3>Statistika posjećenosti</h3>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th class="text-center sort-link"><a
                            href="{% url 'statistika:statistika_sort' 'posjecenost_stranica' %}">Stranica</a></th>
                    <th class="text-center sort-link"><a
                            href="{% url 'statistika:statistika_sort' 'posjecenost_prikaz' %}">Broj prikaza</a></th>
                    <th class="text-center sort-link"><a
                            href="{% url 'statistika:statistika_sort' 'posjecenost_vrijeme' %}">
                        Vrijeme zadržavanja</a></th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <th class="text-center cell">Početna Stranica</th>
                        <th class="text-center cell">{{pocetna.brojprikaza}}</th>
                        <th class="text-center cell">{{pocetna.vrijemezadrzavanja}}</th>
                    </tr>
                    {% for s in statPosj %}
                            <tr>
                                <td class="text-center cell">{{ s.0 }}</td>
                                <td class="text-center cell">{{ s.1 }}</td>
                                <td class="text-center cell">{{ s.2 }}</td>
                            </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
            <h3>Statistika reprodukcija</h3>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th class="text-center sort-link"><a
                            href="{% url 'statistika:statistika_sort' 'reprodukcija_stranica' %}">Stranica</a></th>
                    <th class="text-center sort-link"><a
                            href="{% url 'statistika:statistika_sort' 'reprodukcija_korisnik' %}">
                        Broj reprodukcija korisnika</a></th>
                    <th class="text-center sort-link"><a
                            href="{% url 'statistika:statistika_sort' 'reprodukcija_ukupno' %}">Ukupno reprodukcija</a>
                    </th>
                </tr>
                </thead>

                <tbody>
                {% for izlozak in izlosci %}
                    <tr>
                        <td class="text-center cell">{{ izlozak.nazivizlozak }}</td>
                        <td class="text-center cell">{{ izlozak.idzvucnizapis.brojkorisnika }}</td>
                        <td class="text-center cell">{{ izlozak.idzvucnizapis.brojreprodukcija }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}