app/web/audiseum/android/urls.py
from django.urls import path, re_path
import android.views

app_name = 'android'

urlpatterns = [
    re_path('izlozak(?P<izlozak_id>[0-9]+)/naslov', android.views.android_naslov, name='android_naslov'),
    re_path('izlozak(?P<izlozak_id>[0-9]+)/text', android.views.android_text, name='android_text'),
    re_path('izlozak(?P<izlozak_id>[0-9]+)/audio', android.views.android_audio, name='android_audio'),
    re_path('izlozak(?P<izlozak_id>[0-9]+)/slika', android.views.android_slika, name='android_slika'),
    path('registracija/', android.views.register, name='registracija'),
    path('prijava/', android.views.prijava, name='login'),

    path('statistika/<unique_id>/<izlozak_id>', android.views.android_statistika),
    path('povezi/<unique_id>', android.views.povezi),
    path('odvezi/<unique_id>', android.views.izbrisi_povezanost),
    path('provjeri/<unique_id>', android.views.jel_povezan),
]

app/web/audiseum/audiseum/urls.py
from django.contrib import admin
from django.urls import include, path
import izlosci.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', izlosci.views.index, name='index'),
    path('izlosci/', include('izlosci.urls')),
    path('statistika/', include('statistika.urls')),
    path('android/', include('android.urls')),
]

app/web/audiseum/izlosci/urls.py
from django.urls import path
import izlosci.views
import statistika.views


app_name = 'izlosci'

urlpatterns = [
    path('', izlosci.views.izlosci, name='izlosci'),
    path('grupa/<grupa_id>/', izlosci.views.izlosci_grupa, name='izlosci_grupa'),
    path('izlozak/<izlozak_id>/', izlosci.views.izlozak, name='izlozak'),
    path('promo-materijali/', izlosci.views.promo_materijali, name='promo_materijali'),
    path('registracija/', izlosci.views.register, name='registracija'),
    path('activate/<uidb64>/<token>/', izlosci.views.activate, name='activate'),
    path('prijava/', izlosci.views.prijava, name='login'),
    path('odjava/', izlosci.views.odjava, name='odjava'),
    path('uredi-osobne-podatke/', izlosci.views.uredi_osobne_podatke, name='uredi_osobne_podatke'),
    path('promijeni-lozinku', izlosci.views.promijeni_lozinku, name='promijeni_lozinku'),
    path('../statistika', statistika.views.statistika, name='statistika'),
    path('dodaj-admina/', izlosci.views.dodaj_admina, name='dodaj_admina'),
    path('ovlast/', izlosci.views.dodaj_admin_ovlast, name='ovlast'),
    path('dodaj-izlozak/', izlosci.views.dodaj_izlozak, name='dodaj_izlozak'),
    path('uredi-izlozak/<izlozak_id>/', izlosci.views.uredi_izlozak, name='uredi_izlozak'),
    path('obrisi-izlozak/<izlozak_id>/', izlosci.views.obrisi_izlozak, name='obrisi_izlozak'),
    path('dodaj-grupu/', izlosci.views.dodaj_grupu, name='dodaj_grupu'),
    path('dodaj-promo-materijal', izlosci.views.dodaj_promo_materijal, name='dodaj_promo_materijal'),
    path('reprodukcija/<izlozak_id>', izlosci.views.reproduciraj, name='reproduciraj'),

]

app/web/audiseum/izlosci/models.py
from django.db import models
from datetime import timedelta
from django.conf import settings


class GrupaIzlozaka(models.Model):
    idgrupa = models.AutoField(primary_key=True)
    idnadgrupa = models.IntegerField()
    nazivgrupa = models.CharField(max_length=255)

    class Meta:
        managed = True
        db_table = 'grupeizlozaka'


class Izlozak(models.Model):
    idizlozak = models.AutoField(primary_key=True)
    nazivizlozak = models.CharField(max_length=255)
    opis = models.TextField()
    idzvucnizapis = models.ForeignKey('ZvucniZapis', on_delete=models.CASCADE, db_column='idzvucnizapis')  # ?? on_delete ??
    qrkod = models.CharField(max_length=255)
    idslika = models.ForeignKey('Slika', on_delete=models.CASCADE, db_column='idslika') # ?? on_delete ??
    grupa = models.ManyToManyField(GrupaIzlozaka)

    class Meta:
        managed = True
        db_table = 'izlosci'


class Slika(models.Model):
    idslika = models.AutoField(primary_key=True)
    slika = models.FileField(upload_to='slike/')

    class Meta:
        managed = True
        db_table = 'slike'


class ZvucniZapis(models.Model):
    idzvucnizapis = models.AutoField(primary_key=True)
    zvucnizapis = models.FileField(upload_to='audio/')
    brojkorisnika = models.BigIntegerField(default=0)
    brojreprodukcija = models.BigIntegerField(default=0)

    class Meta:
        managed = True
        db_table = 'zvucnizapisi'


class PromotivniMaterijal(models.Model):
    idmaterijal = models.AutoField(primary_key=True)
    materijal = models.FileField(upload_to='promo/')

    class Meta:
        managed = True
        db_table = 'promotivnimaterijali'


class PosjetStranice(models.Model):
    idposjet = models.AutoField(primary_key=True)
    idstranica = models.ForeignKey('StatistikaPosjecenosti', on_delete=models.CASCADE, db_column='idstranica')
    vrijemeotvaranja = models.DateTimeField()
    vrijemezatvaranja = models.DateTimeField()

    class Meta:
        managed = True
        db_table = 'posjetestranica'


class StranicaIzlozak(models.Model):
    idstranica = models.ForeignKey('StatistikaPosjecenosti', on_delete=models.CASCADE, db_column='idstranica')
    idizlozak = models.ForeignKey('Izlozak', on_delete=models.CASCADE, db_column='idizlozak')

    class Meta:
        managed = True
        db_table = 'stranicaizlozak'


class StatistikaPosjecenosti(models.Model):
    idstranica = models.BigIntegerField(primary_key=True)
    brojprikaza = models.BigIntegerField(default=0)
    vrijemezadrzavanja = models.DurationField(default=timedelta())

    class Meta:
        managed = True
        db_table = 'statistikaposjecenosti'


class StatistikaReprodukcije(models.Model):
    korisnik = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    idzvucnizapis = models.ForeignKey('ZvucniZapis', on_delete=models.CASCADE, db_column='idzvucnizapis')

    class Meta:
        managed = True
        db_table = 'statistikareprodukcija'


class AdministratorskaOvlast(models.Model):
    idovlast = models.AutoField(primary_key=True)
    opis = models.TextField()

    class Meta:
        managed = True
        db_table = 'administratorskeovlasti'


class Ovlasti(models.Model):
    class Meta:
        permissions = (("can_view", "Smije pogledati"),)


class Aplikacija(models.Model):
    aplikacijaid = models.TextField(primary_key=True)
    korisnik = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)

    class Meta:
        managed = True
        db_table = 'aplikacija'

app/web/audiseum/izlosci/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from django.contrib.auth.models import User, Group
from .forms import (
    RegistrationForm, LoginForm,
    UrediOsobnePodatkeForm, PromijeniLozinkuForm,
    AddAdminForm, AdminOvlastForm,
    DodajIzlozakForm, UrediIzlozakForm, ObrisiIzlozakForm,
    AddGroupForm, PromoMaterijalForm)
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from izlosci.tokens import account_activation_token
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
import sendgrid
from sendgrid.helpers.mail import *
import datetime
from django.utils import timezone


# HELPER
def stat_time(request):
    try:
        # provjeri je li zadnja stranica bila otvorena, ako si ti prva, nemoj mijenjati vrijeme provedeno
        id_zadnja_stranica = request.session['id_zadnja_stranica']
        id_zadnji_posjet = request.session['id_zadnji_posjet']
        posjet = PosjetStranice.objects.get(idposjet=id_zadnji_posjet)
        stat = StatistikaPosjecenosti.objects.get(idstranica=id_zadnja_stranica)
        posjet.vrijeme_zatvaranja = timezone.now()
        vrijeme_od_proslog_posjeta = (timezone.now() - posjet.vrijemeotvaranja)
        if vrijeme_od_proslog_posjeta > timedelta(minutes=10):
            vrijeme_od_proslog_posjeta = timedelta(minutes=10)
        stat.vrijemezadrzavanja += vrijeme_od_proslog_posjeta
        stat.save()
        posjet.save()

    except (PosjetStranice.DoesNotExist, KeyError):
        return
    return


# HELPER
def stat_clicks_time(request, id_trenutna_stranica):
    stat_time(request)
    # dodaj statistiku posjecenosti ako ona ne postoji, ako postoji
    try:
        stranica_stat = StatistikaPosjecenosti.objects.get(idstranica=id_trenutna_stranica)

    except StatistikaPosjecenosti.DoesNotExist:
        stranica_stat = StatistikaPosjecenosti(
            idstranica=id_trenutna_stranica, brojprikaza=0, vrijemezadrzavanja=datetime.timedelta(0))
        stranica_stat.save()

    try:
        trenutni_izlozak = Izlozak.objects.get(idizlozak=id_trenutna_stranica)

        try:
            StranicaIzlozak.objects.get(idizlozak=trenutni_izlozak,idstranica=stranica_stat)
        except StranicaIzlozak.DoesNotExist:
            izstr = StranicaIzlozak(idstranica=stranica_stat, idizlozak=trenutni_izlozak)
            izstr.save()

    except Izlozak.DoesNotExist:  # ako izlozak s tim id ne postoji, onda je to pocetna stranica i nista se ne dogadja
        ...

    posjet = PosjetStranice(
        idstranica=stranica_stat,
        vrijemeotvaranja=timezone.now().strftime('%Y-%m-%d %H:%M:%S'),
        vrijemezatvaranja=(timezone.now() + datetime.timedelta(minutes=1)).strftime('%Y-%m-%d %H:%M:%S'))

    stranica_stat.brojprikaza += 1
    stranica_stat.save()
    posjet.save()

    request.session['id_zadnja_stranica'] = id_trenutna_stranica
    request.session['id_zadnji_posjet'] = PosjetStranice.objects.latest('idposjet').idposjet


def android_povezi(request):
    try:  # dio za povezivanje android aplikacije
        unique_id = request.session["unique_id"]
        nova_aplikacija = Aplikacija(aplikacijaid=unique_id, korisnik=request.user,)
        nova_aplikacija.save()
        return True
    except:
        return False


def index(request):
    return redirect('/izlosci')


def nadgrupe(sveGrupe):
    grupeSPodgrupama = set()
    for grupa in sveGrupe:
        if grupa.idgrupa == grupa.idnadgrupa:
            for podgrupa in sveGrupe:
                if podgrupa.idnadgrupa == grupa.idgrupa and podgrupa.idgrupa != podgrupa.idnadgrupa:
                    grupeSPodgrupama.add(grupa.idgrupa)
                    break
    return grupeSPodgrupama


def izlosci(request):
    # statistika za broj posjeta i provedeno vrijeme
    stat_clicks_time(request, 0)

    sviIzlosci = Izlozak.objects.all().order_by('nazivizlozak')
    sveGrupe = GrupaIzlozaka.objects.all().order_by('nazivgrupa')
    grupeSPodgrupama = nadgrupe(sveGrupe)

    context = {'sviIzlosci': sviIzlosci,
               'sveGrupe': sveGrupe,
               'grupeSPodgrupama': grupeSPodgrupama,
               'register_form': RegistrationForm(),
               'login_form': LoginForm(),
               'add_admin_form': AddAdminForm(),
               'admin_ovlast_form': AdminOvlastForm(),
               'dodaj_izlozak_form': DodajIzlozakForm(),
               'add_group_form': AddGroupForm(),
               'promo_materijal_form': PromoMaterijalForm()}
    return render(request, 'izlosci/izlosci.html', context)


def izlosci_grupa(request, grupa_id):
    # statistika za broj posjeta i provedeno vrijeme
    stat_clicks_time(request, 0)

    sviIzlosci = Izlozak.objects.all().order_by('nazivizlozak')
    grupa = GrupaIzlozaka.objects.get(pk=grupa_id)
    sveGrupe = GrupaIzlozaka.objects.all().order_by('nazivgrupa')
    grupeSPodgrupama = nadgrupe(sveGrupe)

    context = {'sviIzlosci': sviIzlosci,
               'sveGrupe': sveGrupe,
               'grupeSPodgrupama': grupeSPodgrupama,
               'grupa': grupa,
               'register_form': RegistrationForm(),
               'login_form': LoginForm(),
               'add_admin_form': AddAdminForm(),
               'admin_ovlast_form': AdminOvlastForm(),
               'dodaj_izlozak_form': DodajIzlozakForm(),
               'add_group_form': AddGroupForm(),
               'promo_materijal_form': PromoMaterijalForm()}
    return render(request, 'izlosci/izlosci.html', context)


def izlozak(request, izlozak_id):
    # statistika za broj posjeta i provedeno vrijeme
    stat_clicks_time(request, izlozak_id)

    izlozak = Izlozak.objects.get(pk=izlozak_id)
    sveGrupe = GrupaIzlozaka.objects.all().order_by('nazivgrupa')
    grupeSPodgrupama = nadgrupe(sveGrupe)

    context = {'izlozak': izlozak,
               'sveGrupe': sveGrupe,
               'grupeSPodgrupama': grupeSPodgrupama,
               'register_form': RegistrationForm(),
               'login_form': LoginForm(),
               'add_admin_form': AddAdminForm(),
               'admin_ovlast_form': AdminOvlastForm(),
               'dodaj_izlozak_form': DodajIzlozakForm(),
               'add_group_form': AddGroupForm(),
               'promo_materijal_form': PromoMaterijalForm()}
    return render(request, 'izlosci/izlozak.html', context)


def promo_materijali(request):
    promoMaterijali = PromotivniMaterijal.objects.all()
    sveGrupe = GrupaIzlozaka.objects.all().order_by('nazivgrupa')
    grupeSPodgrupama = nadgrupe(sveGrupe)

    context = {'promoMaterijali': promoMaterijali,
               'sveGrupe': sveGrupe,
               'grupeSPodgrupama': grupeSPodgrupama,
               'add_admin_form': AddAdminForm(),
               'admin_ovlast_form': AdminOvlastForm(),
               'dodaj_izlozak_form': DodajIzlozakForm(),
               'add_group_form': AddGroupForm(),
               'promo_materijal_form': PromoMaterijalForm()}
    return render(request, 'izlosci/promotivniMaterijali.html', context)


def register(request):
    stat_time(request)  # spremanje provedenog vremena na prethodnoj stranici
    if request.method == 'POST':
        register_form = RegistrationForm(request.POST)
        if register_form.is_valid():
            user = register_form.save(commit=False)
            user.is_active = False
            user.save()  # TODO: ne smije user.save() kad registracija prode a nije prihvacena
            current_site = get_current_site(request)
            message = render_to_string('izlosci/aktivacija_racuna_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': force_text(urlsafe_base64_encode(force_bytes(user.pk))),
                'token': account_activation_token.make_token(user),
            })

            sg = sendgrid.SendGridAPIClient(
                apikey='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')
            from_email = Email(email="no-reply@audiseum.com", name="Aktivacija")
            to_email = Email(user.email)
            subject = "Aktivirajte svoj Audiseum račun"
            content = Content("text/html", message)
            mail = Mail(from_email, subject, to_email, content)
            sg.client.mail.send.post(request_body=mail.get())

            sveGrupe = GrupaIzlozaka.objects.all().order_by('nazivgrupa')
            grupeSPodgrupama = nadgrupe(sveGrupe)
            poruka = 'Molimo Vas aktivirajte svoj korisnički račun klikom na link koji Vam je poslan na e-mail adresu.'
            context = {'sveGrupe': sveGrupe,
                       'grupeSPodgrupama': grupeSPodgrupama,
                       'register_form': RegistrationForm(),
                       'login_form': LoginForm(),
                       'poruka': poruka,
                       'add_admin_form': AddAdminForm(),
                       'admin_ovlast_form': AdminOvlastForm(),
                       'dodaj_izlozak_form': DodajIzlozakForm(),
                       'add_group_form': AddGroupForm(),
                       'promo_materijal_form': PromoMaterijalForm()}
            return render(request, 'izlosci/poruka.html', context)
        else:
            sveGrupe = GrupaIzlozaka.objects.all().order_by('nazivgrupa')
            grupeSPodgrupama = nadgrupe(sveGrupe)
            poruka = 'Registracija nije uspjela! Molimo Vas pokušajte ponovno.'
            context = {'sveGrupe': sveGrupe,
                       'grupeSPodgrupama': grupeSPodgrupama,
                       'register_form': RegistrationForm(),
                       'login_form': LoginForm(),
                       'poruka': poruka,
                       'add_admin_form': AddAdminForm(),

app/web/audiseum/izlosci/templates/izlosci/adminIzlozakView.html
<a class="btn btn-outline-dark fa fa-pencil fa-2x card-btn" role="button"
   href="{% url 'izlosci:uredi_izlozak' izlozak.idizlozak %}" title="Uredi izložak">
</a>
<button class="btn btn-outline-dark fa fa-trash-o fa-2x card-btn" type="button" data-toggle="modal"
        data-target="#deleteExibitModal{{ izlozak.idizlozak }}" title="Obriši izložak">
</button>

<div class="modal fade" id="deleteExibitModal{{ izlozak.idizlozak }}">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <h3>Obriši izložak</h3>
                    </div>
                </div>
            </div>

            <div class="modal-body">
                <form role="form" action="{% url 'izlosci:obrisi_izlozak' izlozak.idizlozak %}" method="POST">
                    {% csrf_token %}
                    <h5>Jeste li sigurni da želite obrisati izložak <b>{{ izlozak.nazivizlozak }}</b>?</h5>
                    <div class="form-group">
                        <input type="submit" class="form-control btn btn-danger submit-btn" value="Obriši izložak">
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col-3">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal" aria-label="Close">
                                Zatvori
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/web/audiseum/izlosci/templates/izlosci/adminView.html
{% load izlosci_extra %}
<button class="btn btn-outline-dark dropdown-toggle btn-admin-izbornik" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="true">
    Izbornik
</button>
<div class="dropdown-menu">
    <div class="btn-group-vertical">
        {% if user|has_group:'vlasnik' %}
            {% include 'izlosci/vlasnikButtonsView.html' %}
        {% endif %}
        <button type="button" class="btn btn-outline-dark" aria-hidden="true" data-toggle="modal"
                data-target="#exibitModal">
            <span class="fa fa-plus"></span> Dodaj izložak
        </button>
        <button type="button" class="btn btn-outline-dark" aria-hidden="true" data-toggle="modal"
                data-target="#groupModal">
            <span class="fa fa-plus"></span> Dodaj grupu
        </button>
        <button type="button" class="btn btn-outline-dark" aria-hidden="true" data-toggle="modal"
                data-target="#promoModal">
            <span class="fa fa-plus"></span> Dodaj promo materijal
        </button>
    </div>
</div>

{% if user|has_group:'vlasnik' %}
    {% include 'izlosci/vlasnikModalsView.html' %}
{% endif %}

<div class="modal fade" id="exibitModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <h3>Dodavanje izloška</h3>
                    </div>
                </div>
            </div>

            <div class="modal-body">
                <form role="form" action="{% url 'izlosci:dodaj_izlozak' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ dodaj_izlozak_form.non_field_errors }}
                    <div class="form-group" >
                        {{ dodaj_izlozak_form.nazivizlozak.errors }}
                        <label for="{{ dodaj_izlozak_form.izlozaknaziv.idNazivIzlozak }}">Naziv</label>
                        {{ dodaj_izlozak_form.nazivizlozak }}
                    </div>
                    <div class="form-group">
                        {{ dodaj_izlozak_form.opis.errors }}
                        <label for="{{ dodaj_izlozak_form.opis.idOpis }}">Opis</label>
                        {{ dodaj_izlozak_form.opis }}
                    </div>
                    <div class="form-group">
                        {{ dodaj_izlozak_form.Grupe.errors }}
                        <label for="{{ dodaj_izlozak_form.grupe.grupeAdd }}">Grupe</label>
                        {{ dodaj_izlozak_form.Grupe }}
                    </div>

                    <!--<div class="form-group">-->
                        <!--<label for="grupaIzloska">Grupa</label>-->
                        <!--<div class="dropdown exibitGroupDropdown" data-name="statuses"-->
                             <!--id="grupaIzloska">-->
                            <!--<button class="btn btn-outline-dark card-btn dropdown-toggle" type="button"-->
                                    <!--data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"-->
                                    <!--id="dropdownExibitGroupMenu">-->
                                <!--Izaberite grupu/e<span class="caret"></span>-->
                            <!--</button>-->
                            <!--<ul class="dropdown-menu" aria-labelledby="dropdownExibitGroupMenu">-->
                                <!--{% for grupa in sveGrupe %}-->
                                    <!--<li>-->
                                        <!--<label class="radio-btn">-->
                                            <!--<input type="checkbox" value='{{ grupa.nazivgrupa }}'>-->
                                            <!--{{ grupa.nazivgrupa }}-->
                                        <!--</label>-->
                                    <!--</li>-->
                                <!--{% endfor %}-->
                                <!--&lt;!&ndash;<li class='text-center'>&ndash;&gt;-->
                                    <!--&lt;!&ndash;<button type='button' class='btn btn-xs btn-default clear close-dropdown' value='Clear'>Clear</button>&ndash;&gt;-->
                                    <!--&lt;!&ndash;<button type='button' class='btn btn-xs btn-default save' value='Save'>Save</button>&ndash;&gt;-->
                                <!--&lt;!&ndash;</li>&ndash;&gt;-->
                            <!--</ul>-->
                        <!--</div>-->
                    <!--</div>-->
                    <div class="form-group">
                        {{ dodaj_izlozak_form.slika.errors }}
                        <label for="{{ dodaj_izlozak_form.slika.idSlika }}">Slika</label>
                        {{ dodaj_izlozak_form.slika }}
                    </div>
                    <div class="form-group">
                        {{ dodaj_izlozak_form.zvucnizapis.errors }}
                        <label for="{{ dodaj_izlozak_form.zvucnizapis.idZvucniZapis }}">Zvučni zapis</label>
                        {{ dodaj_izlozak_form.zvucnizapis }}
                    </div>
                    <div class="form-group">
                        <input type="submit" class="form-control btn btn-success submit-btn" value="Dodaj izložak">
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col-3">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal" aria-label="Close">
                                Zatvori
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="groupModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <h3>Dodavanje grupe izložaka</h3>
                    </div>
                </div>
            </div>

            <div class="modal-body">
                <form role="form" id="addGroupForm" action="{% url 'izlosci:dodaj_grupu' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ add_group_form.nazivgrupa.errors }}
                        <label for="{{ add_group_form.nazivgrupa.nameAddGroup }}">Naziv</label>
                        {{ add_group_form.nazivgrupa }}
                    </div>
                    <div class="form-group">
                        {{ add_group_form.Nadgrupe.errors }}
                        <label for="{{ add_group_form.nadgrupe.nadgrupeAdd }}">Nadgrupe</label>
                        {{ add_group_form.Nadgrupe }}
                        <!--<div class="dropdown nadgrupaDropdown" data-name="statuses" id="nadgrupa">-->
                            <!--<button class="btn btn-outline-dark card-btn dropdown-toggle" type="button"-->
                                    <!--data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"-->
                                    <!--id="nadgrupaDropdownMenu">-->
                                <!--Izaberite grupu/e<span class="caret"></span>-->
                            <!--</button>-->
                            <!--<ul class="dropdown-menu" aria-labelledby="nadgrupaDropdownMenu">-->
                                <!--{% for grupa in sveGrupe %}-->
                                    <!--{% if grupa.idgrupa == grupa.idnadgrupa %}-->
                                        <!--<li>-->
                                            <!--<label class="radio-btn">-->
                                                <!--<input type="checkbox" value='{{ grupa.nazivgrupa }}'>-->
                                                <!--{{ grupa.nazivgrupa }}-->
                                            <!--</label>-->
                                        <!--</li>-->
                                    <!--{% endif %}-->
                                <!--{% endfor %}-->
                            <!--</ul>-->
                        <!--</div>-->
                    </div>
                    <div class="form-group">
                        <input type="submit" class="form-control btn btn-success submit-btn" value="Dodaj grupu izložaka">
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col-3">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal" aria-label="Close">
                                Zatvori
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="promoModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <h3>Dodavanje promotivnog materijala</h3>
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <form role="form" action="{% url 'izlosci:dodaj_promo_materijal' %}" method="POST"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ promo_materijal_form.materijal.errors }}
                        <label for="{{ promo_materijal_form.materijal.idMaterijal }}">Promotivni materijal</label>
                        {{ promo_materijal_form.materijal }}
                    </div>
                    <div class="form-group">
                        <input type="submit" class="form-control btn btn-success submit-btn"
                               value="Dodaj promotivni materijal">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>