app/web/audiseum/android/urls.py
from django.urls import path, re_path
import android.views

app_name = 'android'

urlpatterns = [
    re_path('izlozak(?P<izlozak_id>[0-9]+)/naslov', android.views.android_naslov, name='android_naslov'),
    re_path('izlozak(?P<izlozak_id>[0-9]+)/text', android.views.android_text, name='android_text'),
    re_path('izlozak(?P<izlozak_id>[0-9]+)/audio', android.views.android_audio, name='android_audio'),
    re_path('izlozak(?P<izlozak_id>[0-9]+)/slika', android.views.android_slika, name='android_slika'),
    path('registracija/', android.views.register, name='registracija'),
    path('prijava/', android.views.prijava, name='login'),

    path('statistika/<unique_id>/<izlozak_id>', android.views.android_statistika),
    path('povezi/<unique_id>', android.views.povezi),
    path('odvezi/<unique_id>', android.views.izbrisi_povezanost),
    path('provjeri/<unique_id>', android.views.jel_povezan),
]

app/web/audiseum/audiseum/urls.py
from django.contrib import admin
from django.urls import include, path
import izlosci.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', izlosci.views.index, name='index'),
    path('izlosci/', include('izlosci.urls')),
    path('statistika/', include('statistika.urls')),
    path('android/', include('android.urls')),
]

app/web/audiseum/android/models.py
from django.db import models

# Create your models here.

app/web/audiseum/android/views.py
from django.shortcuts import render
from django.http import HttpResponse
from izlosci.models import Izlozak, ZvucniZapis, Slika, Aplikacija, StatistikaReprodukcije
from izlosci.forms import RegistrationForm, LoginForm
import izlosci.views


def android_naslov(request, izlozak_id):
    izlozak = Izlozak.objects.get(pk=izlozak_id)
    return HttpResponse(str(izlozak.nazivizlozak))


def android_text(request, izlozak_id):
    izlozak = Izlozak.objects.get(pk=izlozak_id)
    return HttpResponse(str(izlozak.opis))


def android_audio(request, izlozak_id):
    izlozak = Izlozak.objects.get(pk=izlozak_id)
    return HttpResponse("http://35.189.113.190:8000/" + str(izlozak.idzvucnizapis.zvucnizapis))


def android_slika(request, izlozak_id):
    izlozak = Izlozak.objects.get(pk=izlozak_id)
    return HttpResponse("http://35.189.113.190:8000/" + str(izlozak.idslika.slika))


def register(request):
    return izlosci.views.register(request)


def prijava(request):
    return izlosci.views.prijava(request)


def povezi(request, unique_id):
    if request.user.is_authenticated:  # ako je korisnik prijavljen onda samo povezi
        nova_aplikacija = Aplikacija(
            aplikacijaid=unique_id,
            korisnik=request.user,
        )
        nova_aplikacija.save()
        return HttpResponse("Povezivanje Uspjesno! Sada se mozete vratiti u aplikaciju")
    else:  # ako korisnik nije prijavljen ga vodi da se prijavi ili registrira
        request.session["unique_id"] = unique_id
        context = {
            'register_form': RegistrationForm(),
            'login_form': LoginForm(),
        }

        return render(request, 'androidLogin.html', context)


def jel_povezan(request, unique_id):
    apps = Aplikacija.objects.filter(aplikacijaid=unique_id)
    if not apps:
        return HttpResponse("nije")
    else:
        return HttpResponse("je")


def izbrisi_povezanost(request, unique_id):
    app = Aplikacija.objects.filter(aplikacijaid=unique_id)
    if app:
        app.delete()
        if request.user.is_authenticated:
            request.user.logout()
        return HttpResponse("Uspjesno")
    return HttpResponse("Neuspjesno")


def android_statistika(request, unique_id, izlozak_id):
    # TODO: integrirati ovo sa android_audio
    obj_zvucnizapis = ZvucniZapis.objects.get(izlozak=izlozak_id)
    try:
        obj_korisnik = (Aplikacija.objects.get(aplikacijaid=unique_id)).korisnik
    except Aplikacija.DoesNotExist:
        obj_korisnik = None

    playback = StatistikaReprodukcije(
        korisnik=obj_korisnik,
        idzvucnizapis=obj_zvucnizapis,
    )
    playback.save()
    obj_zvucnizapis.brojreprodukcija += 1
    obj_zvucnizapis.save()
    return HttpResponse("Uspjesno")

    # code unreachable!?
    # apps = Aplikacija.objects.filter(aplikacijaid=unique_id)
    # if not apps:
    #     return HttpResponse("nije")
    # else:
    #     return HttpResponse("je")

app/web/audiseum/android/templates/androidLogin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Audiseum</title>

    {% load static %}

    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
          crossorigin="anonymous">
</head>

<body>

<div class="container">
    <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
                <a href="#login" class="nav-link active" role="tab" data-toggle="tab" id="loginFormLink"><h2>
                    Prijava</h2></a>
            </li>
            <li class="nav-item">
                <a href="#register" class="nav-link" role="tab" data-toggle="tab" id="registerFormLink"><h2>
                    Registracija</h2></a>
            </li>
    </ul>

    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade active show" id="login">
            <form role="form" id="loginForm" action="{% url 'android:login' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    {{ login_form.username.errors }}
                    <label for="{{ login_form.username.idUsernameLogin }}">Korisničko ime</label>
                    {{ login_form.username }}
                </div>
                <div class="form-group">
                    {{ login_form.password.errors }}
                    <label for="{{ login_form.password.idPassword }}">Lozinka</label>
                    {{ login_form.password }}
                </div>
                <div class="form-group">
                    <input type="submit" class="form-control btn btn-success submit-btn" value="Prijavi se">
                </div>
            </form>
        </div>

        <div role="tabpanel" class="tab-pane fade" id="register">
            <form role="form" id="registerForm" action="{% url 'android:registracija' %}" method="POST">
                {% csrf_token %}
                {{ register_form.non_field_errors }}
                <div class="form-group">
                    {{ register_form.username.errors }}
                    <label for="{{ register_form.username.idUsernameRegister }}">Korisničko ime</label>
                    {{ register_form.username }}
                </div>
                <div class="form-group">
                    {{ register_form.first_name.errors }}
                    <label for="{{ register_form.first_name.idFirstName }}">Ime</label>
                    {{ register_form.first_name }}
                </div>
                <div class="form-group">
                    {{ register_form.last_name.errors }}
                    <label for="{{ register_form.last_name.idLastName }}">Prezime</label>
                    {{ register_form.last_name }}
                </div>
                <div class="form-group">
                    {{ register_form.email.errors }}
                    <label for="{{ register_form.email.idEmail }}">E-mail</label>
                    {{ register_form.email }}
                </div>
                <div class="form-group">
                    {{ register_form.password1.errors }}
                    <label for="{{ register_form.password1.idLozinka }}">Lozinka</label>
                    {{ register_form.password1 }}
                </div>
                <div class="form-group">
                    {{ register_form.password2.errors }}
                    {{ register_form.password2 }}
                </div>
                <div class="form-group">
                    <input type="submit" class="form-control btn btn-success submit-btn" value="Registriraj se">
                </div>
            </form>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</body>
</html>